version: "3.9"
services:
  config-server:
    image: uf13/config-server:11-alpine
    build:
      context: ./confserver
    #ports:
    #  - 9999:9999
    networks:
      af:
  eureka:
    image: uf13/eureka:11-alpine
    build:
      context: ./eureka-server
    #ports: 
    #  - 8761:8761
    networks:
      af:
  mongo: 
    image: mongo:4.4-rc
    # ports: 
    #  - 27017:27017
    healthcheck:
      test: ["CMD", "echo 'db.stats().ok' | mongo 127.0.0.1:27017/test --quiet"]
      interval: 1m
      timeout: 2s
      retries: 3
      start_period: 15s
    volumes:
      - "mongodbdata:/data/db"
      - "mongodbconfig:/data/configdb"
    networks:
      af:
  catalogue:
    image: uf13/catalogue:11-alpine
    build:
      context: ./catalogue
    depends_on:
      config-server:
        condition: service_healthy
      mongo:
        condition: service_started
      eureka:
        condition: service_healthy
    restart: on-failure
    #ports:
    #  - 7777:7777
    networks:
      af:
  purchase:
    image: uf13/purchase:11-alpine
    build:
     context: ./purchase
    depends_on:
      config-server:
        condition: service_healthy
      mongo:
        condition: service_started
      eureka:
        condition: service_healthy
    restart: on-failure
    #ports:
    #  - "7788:7788"
    networks:
      af:
  gateway:
    image: uf13/gateway:11-alpine
    build:
      context: ./gateway
    depends_on:
      eureka:
        condition: service_healthy
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      af:
networks:
  af: 

volumes:
  mongodbdata:
  mongodbconfig:
