version: "3.9"
services:
  config-server:
    image: uf13/config-server:11-alpine
    build:
      context: ./confserver
    ports:
      - 9999:9999
    networks:
      af:
  eureka:
    image: uf13/eureka:11-alpine
    build:
      context: ./eureka-server
    ports: 
      - 8761:8761
    networks:
      af:
  mongo: 
    image: mongo:latest
    ports: 
      - 27017:27017
    volumes:
      - "mongodbdata:/data/db"
    networks:
      af:
  catalogue:
    image: uf13/catalogue:11-alpine
    build:
      context: ./catalogue
    depends_on:
      - config-server
      - mongo
    restart: on-failure
    ports:
      - 7777:7777
    networks:
      af:
  purchase:
    image: uf13/purchase:11-alpine
    build:
     context: ./purchase
    depends_on:
      - config-server
      - mongo
    restart: on-failure
    ports:
      - "7788:7788"
    networks:
      af:
  gateway:
    image: uf13/gateway:11-alpine
    build:
      context: ./gateway
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      af:
networks:
  af: 

volumes:
  mongodbdata:
