spring:
 application:
  name: gateway
 cloud:
  gateway:
   routes:
   - id: catalogueModule
     uri: lb://CATALOGUE
     predicates:
     - Path=/catalogue/**
     filters:
     - StripPrefix=1
   - id: purchaseModule
     uri: lb://PURCHASE
     predicates:
     - Path=/purchase/**
     filters:
     - StripPrefix=1
   - id: authModule
     uri: lb://USER-SERVICE
     predicates:
     - Path=/user-service/**
     filters:
     - StripPrefix=1
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/