spring:
  application:
    name: eureka-server
server:
  port: ${EUREKA_PORT:8761}
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false